### ISSUE TITLE
Package 2.0.0.8 installation fails on PreInstall.vi

### ISSUE THREAD

**Issue by MathieuR-Iolas** [ni/actor-framework#3]
I tried to install the package actor_framework_2024_for_2020-2.0.0.8.vip (from [Builds folder in Cleanup](https://github.com/ni/actor-framework/tree/cleanup/Builds) branch).

I saw the LabVIEW loading dialog box, looking for Stash Framework.vi
![image](https://github.com/user-attachments/assets/3ccc6ba2-a08a-46e2-ba6f-7431a5269d50)

And I finally get an error:
![image](https://github.com/user-attachments/assets/9f2e6e69-f46e-40c1-a51b-b30f35b96b93)

It seems to be a [known behavior](https://forums.vipm.io/topic/2482-subvis-in-prepost-install-vis/): custom actions VIs cannot use sub-VIs that are not already installed by the package. So when installing actor_framework_2024_for_2020-2.0.0.8.vip, the content of the folder Install Support has not yet been copied to their destination. And cannot be loaded by PreInstall.vi.

I get the exact same behavior with LabVIEW 2023 64-bits and LabIVEW 2021 SP1 32-bits.

I suppose (not tested) that this issue will impact the exact same way the PostInstall custom action.

One suggestion could be to set content of the sub-VIs directly in Pre-Install VI (no more sub-VIs calls, lowering readability and maintenability). A more complex approach could be to create a support package, and set it as dependency of actor_framework_2024_for_2020-2.0.0.8.vip: in my understanding, dependencies are supposed to be installed before by VIPM

**Comment by MathieuR-Iolas** [comment]
With the following diagram, the zip file is created as expected at package installation:

![Pre-Install Custom Action](https://github.com/user-attachments/assets/2e8d15ae-e6dc-43b2-bdd1-59a49de2bdfe)

**Comment by niACS** [comment]
This will be fixed once my current pull requests have been processed.  The correct build will be 2.0.0.12 (1.0.0.8 if you are looking at the main branch).
