### ISSUE TITLE
Casting Utility for Actors.vim is missing

### ISSUE THREAD

**Issue by MathieuR-Iolas** [ni/actor-framework#6]
I just installed actor_framework_2024_for_2020-1.0.0.8.vip (from @niACS repo - early test, before pull request has been processed)

It seems that **`Casting Utility For Actors.vim`** is missing - originally located in **`<vi.lib>\ActorFramework\Actor\`**

Existing project has broken Do.vi for (quite) every messages:
![image](https://github.com/user-attachments/assets/5a32611d-d9cd-4242-bc82-e9b52cc9034b)

When creating a new message for an actor, I get a broken Do.vi:
![image](https://github.com/user-attachments/assets/65086529-1e19-40be-a5c5-54843ce97124)

LabVIEW 2023 64-bits

**Comment by MathieuR-Iolas** [comment]
Oops, irrelevant package. My bad.

This said, I do not see any trace of the malleable VI in **`actor_framework_2024_for_2020-2.0.0.12.vip`**:
![image](https://github.com/user-attachments/assets/58434c1d-6d62-4474-83f6-977606d2c4ce)

I revert my VM to a previous snapshot (no traces of previously tested packages), and then installed v2.0.0.12 and I still have the same issue regarding missing `Casting Utility for Actors.vim`.

**Comment by MathieuR-Iolas** [comment]
I do not see this malleable VI in [ni/actor-framework](https://github.com/ni/actor-framework) original repo.
This may explain why it does not appear in @niACS's fork ?

**Comment by svelderrainruiz** [comment]
This issue got fixed on a separate branch. The VI Package that contains the fix is 2.0.0.17. The AF version on this VI Package contains additional functionality to the shipping example from LV2024Q3 AF.

**Comment by MathieuR-Iolas** [comment]
Hi, I tested it on friday, and seems to be okay for me - no more missing VIM.

Opening an existing AF project with the new package installed (2.0.0.17) I get some dialog looking for some Trace VIs missing. Ignoring them, the project can be loaded, run and build as executable. So not a big deal, but perhaps another (small) issue.

**Comment by svelderrainruiz** [comment]
> Hi, I tested it on friday, and seems to be okay - works for me, no more missing VIM.
> 
> Opening an existing AF project with the new package installed (2.0.0.17 in cleanup branch) I get some dialog looking for some Trace VIs missing. Ignoring them, the project can be loaded, run and build as executable. So not a big deal, but perhaps another (small) issue.

Can you please create an issue with the details?
